version: '3.3'
services:
  nginx:
    build: nginx
    ports:
      - '60:80'
      - '550:443'
  mongo:
    image: mongo:4.2.5
    ports:
      - '65015:27017'
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '9090:8080'